name: Deploy to internal test env
on:
  workflow_run:
    workflows: [Contracts CI]
    types: [completed]
    branches: [main]
jobs:
  test_deploy:
    runs-on: contracts
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DEPLOYER_GAS_LIMIT: ${{ secrets.DEPLOYER_GAS_LIMIT }}
      DEPLOYER_TEST_TXNODE: ${{ secrets.DEPLOYER_TEST_TXNODE }}
      DEPLOYER_TEST_KEY: ${{ secrets.DEPLOYER_TEST_KEY }}
    name: test_deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 2 # we want 2 of the latest commit history to identify PR author
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.14.x'
          cache: 'npm'
      - run: npm install
      - name: Prepare Environment
        shell: bash
        run: |
          cp .env.example .env
      - name: Create empty logs directory
        shell: bash
        run: |
          mkdir -p logs
      - name: Create empty addresses directory
        shell: bash
        run: |
          mkdir -p addresses
      - name: Create empty subfolder of addresses directory
        shell: bash
        run: |
          mkdir -p addresses/abis
      - name: Create empty subfolder of test directory
        shell: bash
        run: |
          mkdir -p addresses/abis/test
      - run: npm run deploy-suite:test
      - name: Upload test deploy output
        uses: actions/upload-artifact@v2
        with:
          name: test-deploy-contracts-logs
          path: logs/test.deploy.contracts.txt
      - name: Copy abis from artifacts directory to abis subfolder
        shell: bash
        run: |
          rsync -av --exclude='*.dbg.json' artifacts/contracts/interfaces addresses/abis/test/

      - name: Check Author Name of the PR that merged to main
        run: |
          echo "AUTHOR_NAME=$(git log -n 2 --pretty=format:%an | tail -1)" >> "$GITHUB_ENV"
      - name: Check Author Email of the PR that merged to main
        run: |
          echo "AUTHOR_EMAIL=$(git log -n 2 --pretty=format:%ae | tail -1)" >> "$GITHUB_ENV"
      - name: Check if we can generate a new automated PR
        run: |
          if [[ "$AUTHOR_NAME" == "GitHub Actions Bot" && "$AUTHOR_EMAIL" == "noreply@github.com" ]]; then
              echo "CAN_GENERATE_AUTOMATED_PR=false" >> "$GITHUB_ENV"
          else
              echo "CAN_GENERATE_AUTOMATED_PR=true" >> "$GITHUB_ENV"
          fi
      - name: Create Automated Pull Request
        if: env.CAN_GENERATE_AUTOMATED_PR == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add json file with addresses for test environment.
          committer: GitHub Actions Bot <noreply@github.com>
          author: GitHub Actions Bot <noreply@github.com>
          title: '[Test Environment] New deployed addresses'
          body: >
            This is an auto-generated PR. This PR contains addresses generated after deploy to the internal test environment.
          labels: deployed addresses, automated pr
